ToDoList.WebApp.MVC/Models/ToDoTaskViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoList.WebApp.MVC.Models
{
    public class ToDoTaskViewModel
    {
        public Guid Id { get; set; }

        public DateTimeOffset CreationDateTimeOffset { get; set; }

        [DisplayName("Last Modification")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}")]
        public DateTimeOffset ModificationDateTimeOffset { get; set; }

        public bool IsChecked { get; set; }

        public string Description { get; set; }
    }
}

ToDoList.WebApp.MVC/Controllers/ToDoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using ToDoList.Domain;
using ToDoList.Domain.Commands;
using ToDoList.WebApp.MVC.Models;


namespace ToDoList.WebApp.MVC.Controllers
{
    //[Authorize]
    public class ToDoListController : Controller
    {
        private readonly IToDoListService _toDoListService;

        public ToDoListController(IToDoListService toDoListService)
        {
            _toDoListService = toDoListService;
        }

        public Guid GetUserId()
        {
            try
            {
                return Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == "UserId").Value);
            }
            catch (Exception)
            {
                var name = User.Claims.FirstOrDefault(x => x.Type == "Name") ==null ? "[unknown user]" : User.Claims.FirstOrDefault(x => x.Type == "Name").Value;
                throw new Exception($"Invalid user : {name} has no userId Claim");
            }

        }

        public async Task<IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("UserLogin", "Login");
            }

            var userId = GetUserId();
            var toDoTasks = await _toDoListService.GetByUserId(userId);
            var result = toDoTasks.OrderBy(y => y.CreationDateTimeOffset).
                Select(x => new ToDoTaskViewModel()
            {
                Id = x.Id,
                Description = x.Description,
                IsChecked = x.IsChecked,
                CreationDateTimeOffset = x.CreationDateTimeOffset,
                ModificationDateTimeOffset = x.ModificationDateTimeOffset
            });
            
            return View(result);
        }

        [HttpDelete("todolist/tasks/{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var userId = GetUserId();
            await _toDoListService.DeleteTask(new DeleteToDoTask()
            {
                UserId = userId,
                TaskId = id
            });
            return Json(new { success = true });
        }

        [HttpPut("todolist/tasks/{id:guid}")]
        public async Task<IActionResult> Update(Guid id, [FromBody] JObject task)
        {
            var userId = GetUserId();
            var description = task["Description"]?.ToObject<string>();
            var isChecked = task["IsChecked"]?.ToObject<bool?>();

            await _toDoListService.UpdateTask(new UpdateToDoTask()
            {
                UserId = userId,
                TaskId = id,
                Description = description,
                IsChecked = isChecked
            });

            var updatedTask = await _toDoListService.GetById(userId, id);
            var updatedTaskViewModel = new ToDoTaskViewModel()
            {
                Id = updatedTask.Id,
                ModificationDateTimeOffset = updatedTask.ModificationDateTimeOffset,
                CreationDateTimeOffset = updatedTask.CreationDateTimeOffset,
                IsChecked = updatedTask.IsChecked,
                Description = updatedTask.Description
            };

            return PartialView("_TodoTaskViewModel", updatedTaskViewModel);
        }

        [HttpPost("todolist/tasks")]
        public async Task<IActionResult> Create([FromBody] JObject task)
        {
            var userId = GetUserId();
            var taskId = task["TaskId"].ToObject<Guid>();
            var description = task["Description"].ToObject<string>();

            await _toDoListService.CreateTask(new CreateNewToDoTask()
            {
                UserId = userId,
                TaskId = taskId,
                Description = description
            });

            var createdTask = await _toDoListService.GetById(userId, taskId);
            var createdTaskViewModel = new ToDoTaskViewModel()
            {
                Id = createdTask.Id,
                ModificationDateTimeOffset = createdTask.ModificationDateTimeOffset,
                CreationDateTimeOffset = createdTask.CreationDateTimeOffset,
                IsChecked = createdTask.IsChecked,
                Description = createdTask.Description
            };
            return PartialView("_TodoTaskViewModel", createdTaskViewModel);
        }
    }

    public class CreateTask
    {
        public Guid TaskId { get; set; }
        public string Description { get; set; }
    }
}

ToDoList.WebApp.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList.WebApp.MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="ToDoList" asp-action="Index" class="navbar-brand">ToDoList.WebApp.MVC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Login" asp-action="UserLogin">Login</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ToDoList.WebApp.MVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ToDoList.WebApp.MVC/Views/Shared/_ToDoTaskViewModel.cshtml
@using ToDoList.WebApp.MVC.Models
@model ToDoTaskViewModel
<tr id='@Model.Id'>
    <td style="text-align: center;">
        @Html.CheckBoxFor(model => model.IsChecked, new { htmlAttributes = new { @style = "width:100" },  value="IsChecked" })
    </td>
    <td >
        @Html.DisplayFor(model => model.Description, new { htmlAttributes = new { disabled = true, @readonly = "readonly", @style = "width:100%" } })
    </td>
    <td>
        <input type="button" class="btn btn-default" value="Edit" />
    </td>
    <td>
        <input type="button" class="btn btn-default btn-danger" value="Delete"/>
    </td>

    <td style="text-align:right">
        @Html.DisplayFor(model => model.ModificationDateTimeOffset, new { htmlAttributes = new { disabled = true, @readonly = "readonly" } })
    </td>
</tr>